spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: user
    password: library123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop