spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 1231
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate